### ISSUE TITLE
How to use it with .ovpn file?

### ISSUE THREAD

**Issue by SashaDesigN** [luigiplr/openvpn-bin#2]
Please explain how I can use it? I have Ipvanish with .ovpn files and login/password
I try:

var openvpnmanager = require('node-openvpn');
var openvpnBin = require('openvpn-bin');
var path = require('path');

var filePath = path.normalize('ipvanish/ipvanish-AU-Sydney-syd-a16.ovpn');

   var opts = {
       host: 'syd-a16.ipvanish.com', // normally '127.0.0.1', will default to if undefined
       port: 443, //port openvpn management console
       timeout: 60000, //timeout for connection - optional, will default to 1500ms if undefined
       config: filePath
   };
   var auth = {
       user: 'myemail@gmail.com',
       pass: 'password'
   };

   var openvpn = openvpnmanager.connect(opts)

   openvpn.on('connected', function() { //will be emited on successful interfacing with openvpn instance
       console.log('connected')
       openvpnmanager.authorize(auth).then(function(res){

```
   });
```

   });

   openvpn.on('console-output', function(output) { //emits console output of openvpn instance as a string
       console.log(output)
   });

   openvpn.on('state-change', function(state) { //emits console output of openvpn state as a array
       console.log(state)
   });

   openvpn.on('error', function(error) { //emits console output of openvpn state as a string
       console.log(error)
   });

**Comment by luigiplr** [comment]
Already responded to your issue here: https://github.com/luigiplr/node-openvpn/issues/4
